---
title: "Night of the Kamaitachi: REBIRTH Walkthrough"
description: "A spoiler free Walkthrough for Night of the Kamaitachi: REBIRTH (Kamaitachi no Yoru Rinne Saisei fan-translation)."
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme